### PR TITLE
proto of editing bus message to included more blob meta

### PR DESCRIPTION
**Pull request by wkelly17**
This knowingly does not compile yet because I did not want to change all the renderers without getting Reuben's opinions / work on this, and your review Craig.  

This PR introduces additional metadata from teh rendering process and attaches it to one of the messages currently being sent to the Service Bus.  The upshot of this is to listen for this event in the controller and to then populate the table in the language api that holds the "links" or information about what in which project (or repo or content if you will) may be accessed and in what format.

### CODE REVIEW

**Comment by PurpleGuitar** [comment]
When we discussed this, I was under the impression that we were thinking about including links to the rendered data.  But it looks like you're including the rendered HTML right through the API!  

I'm not necessarily against that, but it's different than I was expecting.  If I understand this right, then we should probably discuss.

**Comment by wkelly17** [comment]
> When we discussed this, I was under the impression that we were thinking about including links to the rendered data. But it looks like you're including the rendered HTML right through the API!
> 
> I'm not necessarily against that, but it's different than I was expecting. If I understand this right, then we should probably discuss.

@PurpleGuitar  - No, this should be links only:  Undoubtedly blob storage is cheaper for this than the postgres storage, and there's certainly no reason to have it as a dup in both spots, other than reducing a potential client's requests by one (e.g. once for the links, and then N number of fetches for whichever blobs are desired).  Overall, The diff is muddy here cause I forget that I have format on save for most projects I'm in, and whatever formatted this isn't the same as whateve Reuben's computer does for formatting, but the relevants bits are here which is the model of what I'd like to attach to the service bus's message.  (namely the url)
https://github.com/WycliffeAssociates/ScriptureRenderingPipeline/pull/91/files#diff-580d7c42598842f77f1d68763d5def08a3fe27993e6e1ff8dd00d3c5cc0596c3

And then here where I add the blobMeta (e.g. its url, sha for that file etc;) to the return service bus message. 
https://github.com/WycliffeAssociates/ScriptureRenderingPipeline/pull/91/files#diff-2ff179eb7c262acccf1e4369a045d7a1555e4552281f238a271f26c3f88bcc07R216-R223

**Review by PurpleGuitar — APPROVED** [review]
The approach seems fine to me.  I'll defer to Reuben on the specifics of the implementation.

**Comment by rbnswartz** [comment]
I'm working on an implementation now

**Pull request closed without merging**
